#include <stddef.h>

typedef unsigned char pcre_uchar;
typedef int BOOL;

typedef struct compile_data {
    pcre_uchar *start_code;
} compile_data;

typedef struct recurse_check {
    struct recurse_check *prev;
    pcre_uchar *group;
} recurse_check;

#define LINK_SIZE 2
#define IMM2_SIZE 2
#define SUPPORT_UTF 1
#define GET(a,b) ((a)[b])
#define GET2(a,b) ((a)[b])
#define HAS_EXTRALEN(c) 0
#define GET_EXTRALEN(c) 0
#define PRIV(x) x

enum {
    OP_CBRA, OP_BRA, OP_ONCE, OP_ONCE_NC, OP_COND, OP_ALT, OP_KET, OP_END,
    OP_ACCEPT, OP_ASSERT_ACCEPT, OP_RECURSE, OP_ASSERT, OP_ASSERT_NOT,
    OP_ASSERTBACK, OP_ASSERTBACK_NOT, OP_MARK, OP_PRUNE_ARG, OP_SKIP_ARG,
    OP_THEN_ARG, OP_CALLOUT, OP_CIRC, OP_CIRCM, OP_CLOSE, OP_COMMIT, OP_CREF,
    OP_DEF, OP_NCREF, OP_NRREF, OP_DOLL, OP_DOLLM, OP_EOD, OP_EODN, OP_FAIL,
    OP_NOT_WORD_BOUNDARY, OP_PRUNE, OP_REVERSE, OP_RREF, OP_SET_SOM, OP_SKIP,
    OP_SOD, OP_SOM, OP_THEN, OP_WORD_BOUNDARY, OP_CHAR, OP_CHARI, OP_NOT,
    OP_NOTI, OP_EXACT, OP_EXACTI, OP_NOTEXACT, OP_NOTEXACTI, OP_TYPEEXACT,
    OP_PROP, OP_NOTPROP, OP_HSPACE, OP_VSPACE, OP_NOT_HSPACE, OP_NOT_VSPACE,
    OP_NOT_DIGIT, OP_DIGIT, OP_NOT_WHITESPACE, OP_WHITESPACE, OP_NOT_WORDCHAR,
    OP_WORDCHAR, OP_ANY, OP_ALLANY, OP_ANYBYTE, OP_CLASS, OP_NCLASS, OP_XCLASS,
    OP_CRSTAR, OP_CRMINSTAR, OP_CRPLUS, OP_CRMINPLUS, OP_CRQUERY, OP_CRMINQUERY,
    OP_CRRANGE, OP_CRMINRANGE, OP_ANYNL, OP_BRAMINZERO, OP_BRAPOS, OP_BRAPOSZERO,
    OP_BRAZERO, OP_CBRAPOS, OP_EXTUNI, OP_KETRMAX, OP_KETRMIN, OP_KETRPOS,
    OP_MINPLUS, OP_MINPLUSI, OP_MINQUERY, OP_MINQUERYI, OP_MINSTAR, OP_MINSTARI,
    OP_MINUPTO, OP_MINUPTOI, OP_NOTMINPLUS, OP_NOTMINPLUSI, OP_NOTMINQUERY,
    OP_NOTMINQUERYI, OP_NOTMINSTAR, OP_NOTMINSTARI, OP_NOTMINUPTO, OP_NOTMINUPTOI,
    OP_NOTPLUS, OP_NOTPLUSI, OP_NOTPOSPLUS, OP_NOTPOSPLUSI, OP_NOTPOSQUERY,
    OP_NOTPOSQUERYI, OP_NOTPOSSTAR, OP_NOTPOSSTARI, OP_NOTPOSUPTO, OP_NOTPOSUPTOI,
    OP_NOTQUERY, OP_NOTQUERYI, OP_NOTSTAR, OP_NOTSTARI, OP_NOTUPTO, OP_NOTUPTOI,
    OP_PLUS, OP_PLUSI, OP_POSPLUS, OP_POSPLUSI, OP_POSQUERY, OP_POSQUERYI,
    OP_POSSTAR, OP_POSSTARI, OP_POSUPTO, OP_POSUPTOI, OP_QUERY, OP_QUERYI,
    OP_REF, OP_REFI, OP_SBRA, OP_SBRAPOS, OP_SCBRA, OP_SCBRAPOS, OP_SCOND,
    OP_SKIPZERO, OP_STAR, OP_STARI, OP_TYPEMINPLUS, OP_TYPEMINQUERY, OP_TYPEMINSTAR,
    OP_TYPEMINUPTO, OP_TYPEPLUS, OP_TYPEPOSPLUS, OP_TYPEPOSQUERY, OP_TYPEPOSSTAR,
    OP_TYPEPOSUPTO, OP_TYPEQUERY, OP_TYPESTAR, OP_TYPEUPTO, OP_UPTO, OP_UPTOI
};

static const unsigned char OP_lengths[] = {0};