#include <stdio.h>
#include <stdint.h>

#define YR_API
#define YR_CONFIG_MAX_STRINGS_PER_RULE 0

typedef struct YR_COMPILER {
    int last_error;
    char* last_error_extra_info;
} YR_COMPILER;

enum {
    ERROR_INSUFFICIENT_MEMORY,
    ERROR_DUPLICATED_IDENTIFIER,
    ERROR_DUPLICATED_STRING_IDENTIFIER,
    ERROR_DUPLICATED_TAG_IDENTIFIER,
    ERROR_DUPLICATED_META_IDENTIFIER,
    ERROR_DUPLICATED_LOOP_IDENTIFIER,
    ERROR_UNDEFINED_STRING,
    ERROR_UNDEFINED_IDENTIFIER,
    ERROR_UNREFERENCED_STRING,
    ERROR_EMPTY_STRING,
    ERROR_NOT_A_STRUCTURE,
    ERROR_NOT_INDEXABLE,
    ERROR_NOT_A_FUNCTION,
    ERROR_INVALID_FIELD_NAME,
    ERROR_MISPLACED_ANONYMOUS_STRING,
    ERROR_INCLUDES_CIRCULAR_REFERENCE,
    ERROR_INCLUDE_DEPTH_EXCEEDED,
    ERROR_LOOP_NESTING_LIMIT_EXCEEDED,
    ERROR_NESTED_FOR_OF_LOOP,
    ERROR_UNKNOWN_MODULE,
    ERROR_INVALID_MODULE_NAME,
    ERROR_DUPLICATED_STRUCTURE_MEMBER,
    ERROR_WRONG_ARGUMENTS,
    ERROR_WRONG_RETURN_TYPE,
    ERROR_INVALID_HEX_STRING,
    ERROR_INVALID_REGULAR_EXPRESSION,
    ERROR_SYNTAX_ERROR,
    ERROR_WRONG_TYPE,
    ERROR_INVALID_MODIFIER,
    ERROR_INVALID_PERCENTAGE,
    ERROR_INTERNAL_FATAL_ERROR,
    ERROR_DIVISION_BY_ZERO,
    ERROR_REGULAR_EXPRESSION_TOO_LARGE,
    ERROR_REGULAR_EXPRESSION_TOO_COMPLEX,
    ERROR_TOO_MANY_STRINGS,
    ERROR_INTEGER_OVERFLOW,
    ERROR_COULD_NOT_READ_FILE,
    ERROR_DUPLICATED_MODIFIER
};

void yr_get_configuration(int config, uint32_t* value);