#include <string.h>

typedef enum {
    SVG_PRESERVEASPECTRATIO_NONE,
    SVG_PRESERVEASPECTRATIO_XMINYMIN,
    SVG_PRESERVEASPECTRATIO_XMIDYMIN,
    SVG_PRESERVEASPECTRATIO_XMAXYMIN,
    SVG_PRESERVEASPECTRATIO_XMINYMID,
    SVG_PRESERVEASPECTRATIO_XMIDYMID,
    SVG_PRESERVEASPECTRATIO_XMAXYMID,
    SVG_PRESERVEASPECTRATIO_XMINYMAX,
    SVG_PRESERVEASPECTRATIO_XMIDYMAX,
    SVG_PRESERVEASPECTRATIO_XMAXYMAX
} SVG_PreserveAspectRatio_Align;

typedef enum {
    SVG_MEETORSLICE_MEET,
    SVG_MEETORSLICE_SLICE
} SVG_MeetOrSlice;

typedef struct {
    int defer;
    SVG_PreserveAspectRatio_Align align;
    SVG_MeetOrSlice meetOrSlice;
} SVG_PreserveAspectRatio;

typedef enum {
    GF_OK = 0,
    GF_NON_COMPLIANT_BITSTREAM
} GF_Err;