#include <stdbool.h>

typedef struct ecma_object_t ecma_object_t;

enum {
    ECMA_BUILTIN_ID_ARRAYBUFFER_PROTOTYPE,
    ECMA_BUILTIN_ID_SHARED_ARRAYBUFFER_PROTOTYPE,
    ECMA_BUILTIN_ID_TYPEDARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_INT8ARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_UINT8ARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_INT16ARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_UINT16ARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_INT32ARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_UINT32ARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_FLOAT32ARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_UINT8CLAMPEDARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_FLOAT64ARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_BIGINT64ARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_BIGUINT64ARRAY_PROTOTYPE,
    ECMA_BUILTIN_ID_ARRAY_PROTOTYPE_UNSCOPABLES,
    ECMA_BUILTIN_ID_ARRAY_ITERATOR_PROTOTYPE,
    ECMA_BUILTIN_ID_ITERATOR_PROTOTYPE,
    ECMA_BUILTIN_ID_STRING_ITERATOR_PROTOTYPE,
    ECMA_BUILTIN_ID_REGEXP_STRING_ITERATOR_PROTOTYPE,
    ECMA_BUILTIN_ID_EVAL_ERROR_PROTOTYPE,
    ECMA_BUILTIN_ID_RANGE_ERROR_PROTOTYPE,
    ECMA_BUILTIN_ID_REFERENCE_ERROR_PROTOTYPE,
    ECMA_BUILTIN_ID_SYNTAX_ERROR_PROTOTYPE,
    ECMA_BUILTIN_ID_GENERATOR_PROTOTYPE,
    ECMA_BUILTIN_ID_TYPE_ERROR_PROTOTYPE,
    ECMA_BUILTIN_ID_AGGREGATE_ERROR_PROTOTYPE,
    ECMA_BUILTIN_ID_URI_ERROR_PROTOTYPE,
    ECMA_BUILTIN_ID_ERROR_PROTOTYPE,
    ECMA_BUILTIN_ID_DATE_PROTOTYPE,
    ECMA_BUILTIN_ID_REGEXP_PROTOTYPE,
    ECMA_BUILTIN_ID_SYMBOL_PROTOTYPE,
    ECMA_BUILTIN_ID_ASYNC_FUNCTION_PROTOTYPE,
    ECMA_BUILTIN_ID_PROMISE_PROTOTYPE,
    ECMA_BUILTIN_ID_MAP_PROTOTYPE,
    ECMA_BUILTIN_ID_SET_PROTOTYPE,
    ECMA_BUILTIN_ID_WEAKMAP_PROTOTYPE,
    ECMA_BUILTIN_ID_WEAKSET_PROTOTYPE,
    ECMA_BUILTIN_ID_MAP_ITERATOR_PROTOTYPE,
    ECMA_BUILTIN_ID_SET_ITERATOR_PROTOTYPE,
    ECMA_BUILTIN_ID_WEAKREF_PROTOTYPE,
    ECMA_BUILTIN_ID_DATAVIEW_PROTOTYPE,
    ECMA_BUILTIN_ID_OBJECT_PROTOTYPE
};

bool ecma_builtin_is_global(ecma_object_t *obj_p);
bool ecma_builtin_is(ecma_object_t *obj_p, int builtin_id);

#define JERRY_UNUSED(x) (void)(x)