#include <stdint.h>

typedef struct {
    uint16_t td_compression;
} TIFFDirectory;

typedef struct {
    TIFFDirectory tif_dir;
} TIFF;

typedef uint32_t ttag_t;

#define TIFFTAG_PREDICTOR 317
#define TIFFTAG_JPEGTABLES 347
#define TIFFTAG_JPEGIFOFFSET 513
#define TIFFTAG_JPEGIFBYTECOUNT 514
#define TIFFTAG_JPEGQTABLES 519
#define TIFFTAG_JPEGDCTABLES 520
#define TIFFTAG_JPEGACTABLES 521
#define TIFFTAG_JPEGPROC 512
#define TIFFTAG_JPEGRESTARTINTERVAL 515
#define TIFFTAG_BADFAXLINES 326
#define TIFFTAG_CLEANFAXDATA 327
#define TIFFTAG_CONSECUTIVEBADFAXLINES 328
#define TIFFTAG_GROUP3OPTIONS 292
#define TIFFTAG_GROUP4OPTIONS 293
#define TIFFTAG_LERC_PARAMETERS 50674

#define COMPRESSION_NONE 1
#define COMPRESSION_LZW 5
#define COMPRESSION_PACKBITS 32773
#define COMPRESSION_THUNDERSCAN 32809
#define COMPRESSION_NEXT 32766
#define COMPRESSION_JPEG 7
#define COMPRESSION_OJPEG 6
#define COMPRESSION_CCITTRLE 2
#define COMPRESSION_CCITTRLEW 3
#define COMPRESSION_CCITTFAX3 4
#define COMPRESSION_CCITTFAX4 8
#define COMPRESSION_JBIG 9
#define COMPRESSION_DEFLATE 32946
#define COMPRESSION_ADOBE_DEFLATE 10
#define COMPRESSION_PIXARLOG 32709
#define COMPRESSION_SGILOG 34476
#define COMPRESSION_SGILOG24 34676
#define COMPRESSION_LZMA 34925
#define COMPRESSION_ZSTD 34926
#define COMPRESSION_LERC 34887