typedef unsigned long VALUE;
typedef unsigned long ID;

VALUE req_class;
VALUE rack_version_val_val;
VALUE stringio_class;
VALUE connect_val;
VALUE content_length_val;
VALUE content_type_val;
VALUE delete_val;
VALUE early_hints_val;
VALUE empty_val;
VALUE get_val;
VALUE head_val;
VALUE http_val;
VALUE https_val;
VALUE options_val;
VALUE patch_val;
VALUE path_info_val;
VALUE post_val;
VALUE put_val;
VALUE query_string_val;
VALUE rack_errors_val;
VALUE rack_hijack_io_val;
VALUE rack_hijack_val;
VALUE rack_hijackq_val;
VALUE rack_input_val;
VALUE rack_logger_val;
VALUE rack_multiprocess_val;
VALUE rack_multithread_val;
VALUE rack_run_once_val;
VALUE rack_upgrade_val;
VALUE rack_url_scheme_val;
VALUE rack_version_val;
VALUE remote_addr_val;
VALUE request_method_val;
VALUE script_name_val;
VALUE server_name_val;
VALUE server_port_val;
VALUE slash_val;
VALUE sse_sym;
VALUE websocket_sym;
ID new_id;

VALUE to_s;
VALUE to_h;
VALUE method;
VALUE script_name;
VALUE path_info;
VALUE query_string;
VALUE server_name;
VALUE server_port;
VALUE remote_addr;
VALUE rack_version;
VALUE rack_url_scheme;
VALUE rack_input;
VALUE rack_errors;
VALUE rack_multithread;
VALUE rack_multiprocess;
VALUE rack_run_once;
VALUE rack_upgrade;
VALUE headers;
VALUE body;
VALUE rack_logger;
VALUE call;

VALUE rb_define_class_under(VALUE, const char*, VALUE);
void rb_define_method(VALUE, const char*, VALUE, int);
ID rb_intern(const char*);
VALUE rb_ary_new();
void rb_ary_push(VALUE, VALUE);
void rb_gc_register_address(VALUE*);
VALUE rb_const_get(VALUE, ID);
VALUE rb_str_new_cstr(const char*);
VALUE ID2SYM(ID);
VALUE rb_cObject;
VALUE INT2NUM(int);