#include <libintl.h>
#include <locale.h>

typedef enum {
    STRINGPREP_OK,
    STRINGPREP_CONTAINS_UNASSIGNED,
    STRINGPREP_CONTAINS_PROHIBITED,
    STRINGPREP_BIDI_BOTH_L_AND_RAL,
    STRINGPREP_BIDI_LEADTRAIL_NOT_RAL,
    STRINGPREP_BIDI_CONTAINS_PROHIBITED,
    STRINGPREP_TOO_SMALL_BUFFER,
    STRINGPREP_PROFILE_ERROR,
    STRINGPREP_FLAG_ERROR,
    STRINGPREP_UNKNOWN_PROFILE,
    STRINGPREP_ICONV_ERROR,
    STRINGPREP_NFKC_FAILED,
    STRINGPREP_MALLOC_ERROR
} Stringprep_rc;

#define PACKAGE ""
#define LOCALEDIR ""