#include <libintl.h>
#include <locale.h>

#define PACKAGE ""
#define LOCALEDIR ""

typedef enum {
    IDNA_SUCCESS,
    IDNA_STRINGPREP_ERROR,
    IDNA_PUNYCODE_ERROR,
    IDNA_CONTAINS_NON_LDH,
    IDNA_CONTAINS_MINUS,
    IDNA_INVALID_LENGTH,
    IDNA_NO_ACE_PREFIX,
    IDNA_ROUNDTRIP_VERIFY_ERROR,
    IDNA_CONTAINS_ACE_PREFIX,
    IDNA_ICONV_ERROR,
    IDNA_MALLOC_ERROR,
    IDNA_DLOPEN_ERROR
} Idna_rc;