#include <stdint.h>

#define WEBSOCKET_FRAME_OPCODE_PING 0x9
#define WEBSOCKET_FRAME_OPCODE_CLOSE 0x8

#define RELAY_CLIENT_MSG_PING 1
#define RELAY_CLIENT_MSG_CLOSE 2
#define RELAY_CLIENT_MSG_STANDARD 0