#include <stdint.h>

typedef struct {
    uint16_t td_compression;
} TIFFDirectory;

typedef struct {
    TIFFDirectory tif_dir;
} TIFF;

typedef uint32_t ttag_t;

#define TIFFTAG_PREDICTOR 1
#define TIFFTAG_JPEGTABLES 2
#define TIFFTAG_JPEGIFOFFSET 3
#define TIFFTAG_JPEGIFBYTECOUNT 4
#define TIFFTAG_JPEGQTABLES 5
#define TIFFTAG_JPEGDCTABLES 6
#define TIFFTAG_JPEGACTABLES 7
#define TIFFTAG_JPEGPROC 8
#define TIFFTAG_JPEGRESTARTINTERVAL 9
#define TIFFTAG_BADFAXLINES 10
#define TIFFTAG_CLEANFAXDATA 11
#define TIFFTAG_CONSECUTIVEBADFAXLINES 12
#define TIFFTAG_GROUP3OPTIONS 13
#define TIFFTAG_GROUP4OPTIONS 14
#define TIFFTAG_LERC_PARAMETERS 15

#define COMPRESSION_LZW 1
#define COMPRESSION_PACKBITS 2
#define COMPRESSION_THUNDERSCAN 3
#define COMPRESSION_NEXT 4
#define COMPRESSION_JPEG 5
#define COMPRESSION_OJPEG 6
#define COMPRESSION_CCITTRLE 7
#define COMPRESSION_CCITTRLEW 8
#define COMPRESSION_CCITTFAX3 9
#define COMPRESSION_CCITTFAX4 10
#define COMPRESSION_JBIG 11
#define COMPRESSION_DEFLATE 12
#define COMPRESSION_ADOBE_DEFLATE 13
#define COMPRESSION_PIXARLOG 14
#define COMPRESSION_SGILOG 15
#define COMPRESSION_SGILOG24 16
#define COMPRESSION_LZMA 17
#define COMPRESSION_ZSTD 18
#define COMPRESSION_LERC 19
#define COMPRESSION_WEBP 20