#include <stddef.h>

typedef int OnigOptionType;
typedef void* OnigSyntaxType;

#define ONIG_SYNTAX_RUBY NULL
#define ONIG_OPTION_IGNORECASE (1<<0)
#define ONIG_OPTION_EXTEND (1<<1)
#define ONIG_OPTION_MULTILINE (1<<2)
#define ONIG_OPTION_SINGLELINE (1<<3)
#define ONIG_OPTION_FIND_LONGEST (1<<4)
#define ONIG_OPTION_FIND_NOT_EMPTY (1<<5)
#define ONIG_SYNTAX_JAVA NULL
#define ONIG_SYNTAX_GNU_REGEX NULL
#define ONIG_SYNTAX_GREP NULL
#define ONIG_SYNTAX_EMACS NULL
#define ONIG_SYNTAX_PERL NULL
#define ONIG_SYNTAX_POSIX_BASIC NULL
#define ONIG_SYNTAX_POSIX_EXTENDED NULL