#include <string.h>

struct stack_st_SRTP_PROTECTION_PROFILE;
typedef struct stack_st_SRTP_PROTECTION_PROFILE STACK_OF_SRTP_PROTECTION_PROFILE;
#define STACK_OF(type) STACK_OF_##type
struct srtp_protection_profile_st;
typedef struct srtp_protection_profile_st SRTP_PROTECTION_PROFILE;

STACK_OF_SRTP_PROTECTION_PROFILE *sk_SRTP_PROTECTION_PROFILE_new_null(void);
int sk_SRTP_PROTECTION_PROFILE_find(STACK_OF_SRTP_PROTECTION_PROFILE *sk, SRTP_PROTECTION_PROFILE *p);
int sk_SRTP_PROTECTION_PROFILE_push(STACK_OF_SRTP_PROTECTION_PROFILE *sk, SRTP_PROTECTION_PROFILE *p);
void sk_SRTP_PROTECTION_PROFILE_free(STACK_OF_SRTP_PROTECTION_PROFILE *sk);
int find_profile_by_name(const char *name, SRTP_PROTECTION_PROFILE **pp, int len);
void SSLerr(int func, int reason);

#define SSL_F_SSL_CTX_MAKE_PROFILES 0
#define SSL_R_SRTP_COULD_NOT_ALLOCATE_PROFILES 0
#define SSL_R_BAD_SRTP_PROTECTION_PROFILE_LIST 0
#define SSL_R_SRTP_UNKNOWN_PROTECTION_PROFILE 0